In [1]:
#journal lists in journal sources are used: doaj added record, doaj removed record

In [2]:
import pandas as pd

In [3]:
doaj_added_table = pd.read_csv('./journal_lists/DOAJ_ journals_added_6_15.csv')

In [4]:
from datetime import datetime

In [5]:
def get_date(dt):
    try:
        dt = dt.replace("Jan-","January-")
        dt = dt.replace("Feb-","February-")
        dt = dt.replace("Mar-","March-")
        dt = dt.replace("Apr-","April-")
        dt = dt.replace("Jun-","June-")
        dt = dt.replace("Jul-","July-")
        dt = dt.replace("Aug-","August-")
        dt = dt.replace("Sep-","September-")
        dt = dt.replace("Oct-","October-")
        dt = dt.replace("Nov-","November-")
        dt = dt.replace("Dec-","December-")
        
        if int(dt.split('-')[-1]) < 1677:
            return None
        return datetime.strptime(dt, '%d-%B-%Y')
    except:
        return None

In [6]:
def get_date2(dt):
    import datetime
    try:
        if ' ' in str(dt):
            tmp = str(dt).split(' ')[0].split('-')
        else:
            tmp = str(dt).split('-')
        year = int(tmp[0])
        month = int(tmp[1])
        day = int(tmp[2])
        
        if year < 1677:
            return None
        return datetime.datetime(year, month, day)
    except:
        return None

In [7]:
doaj_added_table.shape

(15296, 6)

In [8]:
doaj_added_table.head(50)

,Journal Title,ISSN,Date Added (dd/mm/yy),Seal?,Continuation?,Unnamed: 5
0,Academia Lasalliana Journal of Education and H...,2799-144X,16-June-2022,NaN,NaN,NaN
1,İstanbul Üniversitesi Çeviribilim Dergisi,1309-6214,16-June-2022,NaN,NaN,NaN
2,Annals of Forest Science,1297-966X,15-June-2022,NaN,NaN,NaN
3,The Oncologist,1549-490X,15-June-2022,NaN,NaN,NaN
4,Journal of Industrial Microbiology and Biotech...,1476-5535,15-June-2022,NaN,NaN,NaN
5,Edutainment: Jurnal Ilmu Pendidikan dan Kepend...,2656-5854,15-June-2022,NaN,NaN,NaN
6,Andalasian International Journal of Applied Sc...,2797-0442,15-June-2022,NaN,NaN,NaN
7,Advanced Membranes,2772-8234,15-June-2022,NaN,NaN,NaN
8,Artl@s Bulletin,2264-2668,15-June-2022,NaN,NaN,NaN
9,MRIMS Journal of Health Sciences,2321-7294,15-June-2022,NaN,NaN,NaN
10,Journal of Popular Romance Studies,2159-4473,14-June-2022,NaN,NaN,NaN
11,Advances in Archaeomaterials,2667-1360,14-June-2022,NaN,NaN,NaN
12,Transmotion,2059-0911,14-June-2022,NaN,NaN,NaN
13,Multimodal Transportation,2772-5863,13-June-2022,NaN,NaN,NaN
14,International Journal of Applied Earth Observa...,1872-826X,13-June-2022,NaN,NaN,NaN
15,Complex System Modeling and Simulation,2096-9929,13-June-2022,NaN,NaN,NaN
16,Анналы клинической и экспериментальной неврологии,2075-5473,12-June-2022,Seal,NaN,NaN
17,مجلة المختار للعلوم,2617-2178,11-June-2022,NaN,NaN,NaN
18,Journal de la Faculté de Médecine d'Oran,2571-9874,11-June-2022,NaN,NaN,NaN
19,Indonesian Journal of Educational Development,2722-1059,10-June-2022,NaN,NaN,NaN
20,Societas Dei: Jurnal Agama dan Masyarakat,2599-3267,10-June-2022,NaN,NaN,NaN
21,Abdimas: Jurnal Pengabdian Masyarakat Universi...,2548-7159,10-June-2022,NaN,NaN,NaN
22,Waraqat: Jurnal Ilmu-Ilmu Keislaman,2655-9196,10-June-2022,NaN,NaN,NaN
23,Ajudikasi,2614-0179,9-June-2022,NaN,NaN,NaN
24,Al-Musannif,2684-7736,9-June-2022,NaN,NaN,NaN
25,Animal Frontiers,2160-6064,9-June-2022,NaN,NaN,NaN
26,Acta Theologica,2309-9089,9-June-2022,NaN,NaN,NaN
27,Археология евразийских степей,2587-6112,9-June-2022,NaN,NaN,NaN
28,Cleaner Chemical Engineering,2772-7823,9-June-2022,NaN,NaN,NaN
29,آینده پژوهی ایران,2676-6183,9-June-2022,NaN,NaN,NaN
30,Social Anthropology,1469-8676,8-June-2022,NaN,NaN,NaN
31,IEEE Open Journal of the Solid-State Circuits ...,2644-1349,8-June-2022,NaN,NaN,NaN
32,Journal of Social Computing,2688-5255,8-June-2022,NaN,NaN,NaN
33,International Journal of Personality Psychology,2451-9243,8-June-2022,NaN,NaN,NaN
34,"International Research Journal of Science, Tec...",2799-0648,8-June-2022,NaN,NaN,NaN
35,Natural Hazards Research,2666-5921,8-June-2022,NaN,NaN,NaN
36,JISAE (Journal of Indonesian Student Assessmen...,2597-8934,8-June-2022,NaN,NaN,NaN
37,African Human Mobility Review,2411-6955,8-June-2022,NaN,NaN,NaN
38,JEMDSA,1608-9677,8-June-2022,NaN,NaN,NaN
39,Journal of Educational Research in Mathematics,2288-8357,8-June-2022,NaN,NaN,NaN
40,Uktub,2807-341X,8-June-2022,NaN,NaN,NaN
41,BMC Primary Care,2731-4553,7-June-2022,NaN,Yes,NaN
42,Agriculture & Food Security,2048-7010,7-June-2022,NaN,NaN,NaN
43,PLOS Climate,2767-3200,7-June-2022,NaN,NaN,NaN
44,Intelligent and Converged Networks,2708-6240,7-June-2022,NaN,NaN,NaN
45,"Groups, Geometry and Dynamics",1661-7215,7-June-2022,NaN,NaN,NaN
46,Interfaces and Free Boundaries,1463-9971,7-June-2022,NaN,NaN,NaN
47,Quantum Topology,2415-6302,7-June-2022,NaN,NaN,NaN
48,AGU Advances,2576-604X,7-June-2022,NaN,NaN,NaN
49,Negrei: Academic Journal of Law and Governance,2798-3803,7-June-2022,NaN,NaN,NaN

In [9]:
doaj_added_table['Add_Date'] = doaj_added_table['Date Added (dd/mm/yy)'].apply(get_date)
doaj_added_table['Remove_Date'] = '1677-09-22'
doaj_added_table['Remove_Date'] = doaj_added_table['Remove_Date'].apply(get_date2)

In [10]:
doaj_added_table.shape

(15296, 8)

In [11]:
doaj_added_table

,Journal Title,ISSN,Date Added (dd/mm/yy),Seal?,Continuation?,Unnamed: 5,Add_Date,Remove_Date
0,Academia Lasalliana Journal of Education and H...,2799-144X,16-June-2022,NaN,NaN,NaN,2022-06-16,1677-09-22
1,İstanbul Üniversitesi Çeviribilim Dergisi,1309-6214,16-June-2022,NaN,NaN,NaN,2022-06-16,1677-09-22
2,Annals of Forest Science,1297-966X,15-June-2022,NaN,NaN,NaN,2022-06-15,1677-09-22
3,The Oncologist,1549-490X,15-June-2022,NaN,NaN,NaN,2022-06-15,1677-09-22
4,Journal of Industrial Microbiology and Biotech...,1476-5535,15-June-2022,NaN,NaN,NaN,2022-06-15,1677-09-22
...,...,...,...,...,...,...,...,...
15291,Earth Surface Dynamics,2196-6311,8-May-2014,Seal,NaN,NaN,2014-05-08,1677-09-22
15292,Revista Brasileira de Gestão e Inovação,2319-0639,7-May-2014,NaN,NaN,NaN,2014-05-07,1677-09-22
15293,Electronic Journal of Islamic and Middle Easte...,1664-5707,7-May-2014,NaN,NaN,NaN,2014-05-07,1677-09-22
15294,Revista Digital de Derecho Administrativo,2145-2946,6-May-2014,NaN,NaN,NaN,2014-05-06,1677-09-22
15295,Revista Brasileira de Prescrição e Fisiologia ...,1981-9900,5-May-2014,NaN,NaN,NaN,2014-05-05,1677-09-22

In [12]:
doaj_added_table.dropna(subset=['Add_Date']).shape

(15286, 8)

In [13]:
doaj_added_table['Journal Title'] = doaj_added_table['Journal Title'].str.strip()

In [14]:
doaj_added_table.dropna(subset=['Add_Date'])

,Journal Title,ISSN,Date Added (dd/mm/yy),Seal?,Continuation?,Unnamed: 5,Add_Date,Remove_Date
0,Academia Lasalliana Journal of Education and H...,2799-144X,16-June-2022,NaN,NaN,NaN,2022-06-16,1677-09-22
1,İstanbul Üniversitesi Çeviribilim Dergisi,1309-6214,16-June-2022,NaN,NaN,NaN,2022-06-16,1677-09-22
2,Annals of Forest Science,1297-966X,15-June-2022,NaN,NaN,NaN,2022-06-15,1677-09-22
3,The Oncologist,1549-490X,15-June-2022,NaN,NaN,NaN,2022-06-15,1677-09-22
4,Journal of Industrial Microbiology and Biotech...,1476-5535,15-June-2022,NaN,NaN,NaN,2022-06-15,1677-09-22
...,...,...,...,...,...,...,...,...
15291,Earth Surface Dynamics,2196-6311,8-May-2014,Seal,NaN,NaN,2014-05-08,1677-09-22
15292,Revista Brasileira de Gestão e Inovação,2319-0639,7-May-2014,NaN,NaN,NaN,2014-05-07,1677-09-22
15293,Electronic Journal of Islamic and Middle Easte...,1664-5707,7-May-2014,NaN,NaN,NaN,2014-05-07,1677-09-22
15294,Revista Digital de Derecho Administrativo,2145-2946,6-May-2014,NaN,NaN,NaN,2014-05-06,1677-09-22
15295,Revista Brasileira de Prescrição e Fisiologia ...,1981-9900,5-May-2014,NaN,NaN,NaN,2014-05-05,1677-09-22

In [15]:
doaj_added_table2 = doaj_added_table.dropna(subset=['Add_Date']).groupby(['Journal Title','ISSN','Remove_Date'])['Add_Date'].max().reset_index()

In [16]:
doaj_added_table2.tail(5)

,Journal Title,ISSN,Remove_Date,Add_Date
15201,대한영상의학회지,2288-2928,1677-09-22,2019-11-05
15202,선진국방연구,2635-5531,1677-09-22,2019-02-27
15203,치위생과학회지 (journal of Dental Hygiene Sceince),2233-7679,1677-09-22,2020-08-10
15204,한국균학회지,2383-5249,1677-09-22,2019-09-25
15205,한국치위생학회지 (Journal of Korean Society of Dental...,2288-2294,1677-09-22,2019-11-20

In [17]:
doaj_add_table_simple = doaj_added_table2[['Journal Title','ISSN','Remove_Date','Add_Date']]

In [18]:
doaj_add_table_simple['ISSN'] = doaj_add_table_simple['ISSN'].str.strip()

In [19]:
doaj_add_table_simple.head(5)

,Journal Title,ISSN,Remove_Date,Add_Date
0,"#Tear: Revista de Educação, Ciência e Tecnologia",2238-8079,1677-09-22,2015-07-20
1,(En)clave Comahue,2545-6466,1677-09-22,2019-05-13
2,(پژوهش حسابداری و حسابرسی (پیوسته,2676-7554,1677-09-22,2020-05-25
3,027.7 : Zeitschrift für Bibliothekskultur,2296-0597,1677-09-22,2015-12-21
4,100-Cs,0719-5737,1677-09-22,2018-12-27

In [20]:
doaj_add_table_simple['Journal_Title_Normalized'] = doaj_add_table_simple['Journal Title'].str.lower()

In [21]:
doaj_add_table_final = doaj_add_table_simple.drop_duplicates(subset=['Journal_Title_Normalized'])

In [22]:
doaj_add_table_final.head(3)

,Journal Title,ISSN,Remove_Date,Add_Date,Journal_Title_Normalized
0,"#Tear: Revista de Educação, Ciência e Tecnologia",2238-8079,1677-09-22,2015-07-20,"#tear: revista de educação, ciência e tecnologia"
1,(En)clave Comahue,2545-6466,1677-09-22,2019-05-13,(en)clave comahue
2,(پژوهش حسابداری و حسابرسی (پیوسته,2676-7554,1677-09-22,2020-05-25,(پژوهش حسابداری و حسابرسی (پیوسته

In [23]:
doaj_add_table_final.shape

(15049, 5)

In [24]:
doaj_remove_table = pd.read_csv('./journal_lists/DOAJ_ journals_removed_6_15.csv')

In [25]:
doaj_remove_table.shape

(4784, 5)

In [26]:
doaj_remove_table.head(5)

,Journal Title,ISSN,Date Removed (dd/mm/yyyy),Reason,Unnamed: 4
0,پژوهش‌نامه‌ی آموزش زبان فارسی به غیرفارسی‌زبانان,2676-3354,15-June-2022,Journal not adhering to Best practice,NaN
1,Educational Measurement,2476-6240,15-June-2022,Journal not adhering to Best practice. Ceased ...,NaN
2,Journal of Research in Medical and Dental Science,2347-2367,14-June-2022,Suspected editorial misconduct by publisher,NaN
3,Marine Biodiversity Records,1755-2672,13-June-2022,Ceased publishing,NaN
4,Recent Advances in Biology and Medicine,2378-654X,13-June-2022,Journal is no longer Open Access,NaN

In [27]:
doaj_remove_table['Reason'].unique()

array(['Journal not adhering to Best practice',
       'Journal not adhering to Best practice. Ceased publishing.',
       'Suspected editorial misconduct by publisher', 'Ceased publishing',
       'Journal is no longer Open Access', 'Web site URL no longer works',
       'Inactive (has not published in the last calendar year)',
       'Inactive (has not published in the last calendar year, continuation not in DOAJ)',
       "Changed publisher but hasn't supplied new URLs/site", '?',
       'Ceased publishing + forbidden to open the journal',
       'Has not published enough articles this calendar year', 'Inactive',
       'Broken Links and No reply to emails',
       'Journal not adhering to best practice',
       'Inactive (has not published since 2016)',
       'Journal not adhering to Best practice, no response',
       'no longer published by Sciendo failed to provide update',
       'Website URLs have security issues', 'Not a research journal',
       'No longer OA / Inactive (has not published in the last calendar year)',
       'Journal does not satisfy basic criteria',
       'Has not published enough articles in the last calendar year',
       'No longer OA', 'Inactive (not published since 2018)',
       'Inactive (not published since 2017)',
       'Inactive (not published since 2016)',
       'Inactive (not published since 2015)',
       'Inactive (not published in 2019)', 'Ceased publishing Dec 2019',
       "Journal doesn't adhere to best practice",
       'Website URLs no longer work',
       "Changed publisher but hasn't supplied new url:s/site",
       'Website URL no longer works', 'Site not secure',
       'Has not published enough articles in last calendar year',
       'Suspected editorial misconduct by society',
       'No licence nor OA statement',
       'Journal not adhering to Best Practice', 'ISSN not registered',
       'Requires user registration', 'Missing OA statement',
       'Malicious website', 'No OA statement', 'site unstable',
       'site not secure', 'No license nor OA statement',
       'Not enough articles published', 'No license',
       '24 months embargo ', 'requires user registration to access PDFs',
       'Journal ceased', 'Invalid contact information',
       'no licence no OA statement', 'No longer scholarly journal',
       'No issue published in 2016',
       'Publisher failed to respond to requests for information',
       'no licence', 'no OA and licence', 'no OA statement no licence',
       'Embargo on articles', 'No info on license',
       'Not complying to the BOAI', 'Has not published enough articles',
       'site under reconstruction',
       'Journal not adhering to Best practice (one url per issue)',
       'No licence', 'not open access', 'inactive', 'stopped publishing',
       'Missing license and copyright statement', 'no OA statement',
       'Journal is not Open Access', 'ceased publication ',
       'journal no longer open access', 'not enough articles in 2016',
       'Inactive journal',
       'Journal not adhering to Best practice and issn dead',
       'Web site URL will change',
       'Ceased publishing, no OA statement  no licence',
       'no OA statement  no licence',
       'Ceased publishing, continued by 2164-9170',
       'no licence, no OA statement', 'few articles published',
       'No license nor Open Access statement',
       'Reapp. not adhering to Best practice', 'dead',
       'No editorial board', 'Invalid ISSN', 'Inactive ',
       'No licence , peer review inadequate',
       'No open access licensing terms',
       'no open access licensing description',
       'no open access licensing terms', 'no licensing, ',
       'Not in the issn database', 'No OA or licence info',
       'use of fake impact factor', nan, 'No licence info',
       'application form no info', 'not Open Access', 'book reviews only',
       'Journal is not open access', 'no answer',
       'journal not open access ', 'journal not open access',
       'journal not open access (no statement)',
       'Journal not open access',
       'Inactive (has not published in the last calender year)',
       'Journal is no longer open access',
       'has not published enough articles this calendar year',
       'Other:website closed by publisher', 'No OA statement or licence',
       'No communication ', 'the print title was added to Doaj',
       'Publisher will not submit a new application within the given time period for reapplications',
       'Web site URL no longer works (Ukrainian)',
       'Website URL no longer works\n', "Removed at publisher's request",
       'Journal not adhering to Best Practice\n', 'No longer open access',
       'BMC stopped publishing', 'web site url no longer works',
       'Web site url no longer works', 'Web site url no longer works\n',
       '"     "                    "          "         "',
       'get warning when trying to open journal',
       'the issn 20888708 given by editor leads to another journal',
       'Other'], dtype=object)

In [28]:
doaj_remove_table['Remove_Date'] = doaj_remove_table['Date Removed (dd/mm/yyyy)'].apply(get_date)
doaj_remove_table['Add_Date'] = '1677-09-22'
doaj_remove_table['Add_Date'] = doaj_remove_table['Add_Date'].apply(get_date2)

In [29]:
doaj_remove_table['Journal Title'] = doaj_remove_table['Journal Title'].str.strip()

In [30]:
doaj_remove_table.head(5)

,Journal Title,ISSN,Date Removed (dd/mm/yyyy),Reason,Unnamed: 4,Remove_Date,Add_Date
0,پژوهش‌نامه‌ی آموزش زبان فارسی به غیرفارسی‌زبانان,2676-3354,15-June-2022,Journal not adhering to Best practice,NaN,2022-06-15,1677-09-22
1,Educational Measurement,2476-6240,15-June-2022,Journal not adhering to Best practice. Ceased ...,NaN,2022-06-15,1677-09-22
2,Journal of Research in Medical and Dental Science,2347-2367,14-June-2022,Suspected editorial misconduct by publisher,NaN,2022-06-14,1677-09-22
3,Marine Biodiversity Records,1755-2672,13-June-2022,Ceased publishing,NaN,2022-06-13,1677-09-22
4,Recent Advances in Biology and Medicine,2378-654X,13-June-2022,Journal is no longer Open Access,NaN,2022-06-13,1677-09-22

In [31]:
doaj_remove_table.shape

(4784, 7)

In [32]:
doaj_remove_table.dropna(subset=['Remove_Date']).shape

(4641, 7)

In [33]:
doaj_remove_table2 =  doaj_remove_table.dropna(subset=['Remove_Date']).sort_values('Remove_Date').drop_duplicates(['Journal Title','ISSN','Add_Date'], keep='last')

In [34]:
doaj_remove_table2.shape

(4579, 7)

In [35]:
doaj_remove_table_simple = doaj_remove_table2[['Journal Title','ISSN','Reason','Add_Date','Remove_Date']]

In [36]:
doaj_add_table_simple.shape

(15206, 5)

In [37]:
doaj_remove_table_simple['Journal_Title_Normalized'] = doaj_remove_table_simple['Journal Title'].str.lower()

/tmp/ipykernel_22781/594330670.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  doaj_remove_table_simple['Journal_Title_Normalized'] = doaj_remove_table_simple['Journal Title'].str.lower()

In [38]:
doaj_remove_table_final = doaj_remove_table_simple.drop_duplicates(subset=['Journal_Title_Normalized'])

In [39]:
doaj_all = pd.concat([doaj_add_table_final,doaj_remove_table_final])

In [40]:
doaj_all

,Journal Title,ISSN,Remove_Date,Add_Date,Journal_Title_Normalized,Reason
0,"#Tear: Revista de Educação, Ciência e Tecnologia",2238-8079,1677-09-22,2015-07-20,"#tear: revista de educação, ciência e tecnologia",NaN
1,(En)clave Comahue,2545-6466,1677-09-22,2019-05-13,(en)clave comahue,NaN
2,(پژوهش حسابداری و حسابرسی (پیوسته,2676-7554,1677-09-22,2020-05-25,(پژوهش حسابداری و حسابرسی (پیوسته,NaN
3,027.7 : Zeitschrift für Bibliothekskultur,2296-0597,1677-09-22,2015-12-21,027.7 : zeitschrift für bibliothekskultur,NaN
4,100-Cs,0719-5737,1677-09-22,2018-12-27,100-cs,NaN
...,...,...,...,...,...,...
4,Recent Advances in Biology and Medicine,2378-654X,2022-06-13,1677-09-22,recent advances in biology and medicine,Journal is no longer Open Access
3,Marine Biodiversity Records,1755-2672,2022-06-13,1677-09-22,marine biodiversity records,Ceased publishing
2,Journal of Research in Medical and Dental Science,2347-2367,2022-06-14,1677-09-22,journal of research in medical and dental science,Suspected editorial misconduct by publisher
1,Educational Measurement,2476-6240,2022-06-15,1677-09-22,educational measurement,Journal not adhering to Best practice. Ceased ...
0,پژوهش‌نامه‌ی آموزش زبان فارسی به غیرفارسی‌زبانان,2676-3354,2022-06-15,1677-09-22,پژوهش‌نامه‌ی آموزش زبان فارسی به غیرفارسی‌زبانان,Journal not adhering to Best practice

In [41]:
doaj_all['Add_Date'] = pd.to_datetime(doaj_all['Add_Date'])

In [42]:
doaj_all['Remove_Date'] = pd.to_datetime(doaj_all['Remove_Date'])

In [43]:
doaj_remove_table_simple[doaj_remove_table_simple['Journal Title'] == 'Recent Advances in Biology and Medicine']

,Journal Title,ISSN,Reason,Add_Date,Remove_Date,Journal_Title_Normalized
4,Recent Advances in Biology and Medicine,2378-654X,Journal is no longer Open Access,1677-09-22,2022-06-13,recent advances in biology and medicine

In [44]:
doaj_remove_table2[doaj_remove_table2['Journal Title'] == 'Recent Advances in Biology and Medicine']

,Journal Title,ISSN,Date Removed (dd/mm/yyyy),Reason,Unnamed: 4,Remove_Date,Add_Date
4,Recent Advances in Biology and Medicine,2378-654X,13-June-2022,Journal is no longer Open Access,NaN,2022-06-13,1677-09-22

In [45]:
doaj_all[doaj_all['Journal Title'] == 'Recent Advances in Biology and Medicine']

,Journal Title,ISSN,Remove_Date,Add_Date,Journal_Title_Normalized,Reason
10843,Recent Advances in Biology and Medicine,2378-654X,1677-09-22,2016-02-17,recent advances in biology and medicine,NaN
4,Recent Advances in Biology and Medicine,2378-654X,2022-06-13,1677-09-22,recent advances in biology and medicine,Journal is no longer Open Access

In [46]:
doaj_all.drop_duplicates(subset=['Journal Title']).shape

(17986, 6)

In [47]:
doaj_all_label = doaj_all.groupby(['Journal_Title_Normalized']).apply(lambda g: (max(pd.to_datetime(g.Add_Date)) > max(pd.to_datetime(g.Remove_Date)))).reset_index(name='added')

In [48]:
from datetime import datetime

In [49]:
doaj_all_label[doaj_all_label['added']==False]

                                Journal_Title_Normalized  added
9                                              3 biotech  False
14     452º f : revista de teoría de la literatura y ...  False
18                       a barriguda: revista científica  False
19                                     a contracorriente  False
29                      aaup journal of academic freedom  False
...                                                  ...    ...
17676                                        آب و فاضلاب  False
17709                             اندیشه‌های نوین تربیتی  False
17854                                      مدیریت اسلامی  False
17912                       پژوهشهای زبان و ادبیات فارسی  False
17916   پژوهش‌نامه‌ی آموزش زبان فارسی به غیرفارسی‌زبانان  False

[4232 rows x 2 columns]

In [50]:
doaj_all_label[doaj_all_label['added']==True]

                                Journal_Title_Normalized  added
0       #tear: revista de educação, ciência e tecnologia   True
1                                      (en)clave comahue   True
2                      (پژوهش حسابداری و حسابرسی (پیوسته   True
3              027.7 : zeitschrift für bibliothekskultur   True
4                                                 100-cs   True
...                                                  ...    ...
17950                                           대한영상의학회지   True
17951                                             선진국방연구   True
17952        치위생과학회지 (journal of dental hygiene sceince)   True
17953                                             한국균학회지   True
17954  한국치위생학회지  (journal of korean society of dental...   True

[13723 rows x 2 columns]

In [52]:
doaj_remove_label_all = doaj_all_label[doaj_all_label['added'] == 0].dropna()

In [53]:
doaj_remove_label_all_info = doaj_remove_label_all.merge(doaj_remove_table_final,on=['Journal_Title_Normalized'])

In [54]:
doaj_remove_label_all_info.shape

(4232, 7)

In [55]:
doaj_remove_label_all_info

,Journal_Title_Normalized,added,Journal Title,ISSN,Reason,Add_Date,Remove_Date
0,3 biotech,False,3 Biotech,2190-5738,Journal is no longer Open Access,1677-09-22,2017-01-06
1,452º f : revista de teoría de la literatura y ...,False,452º F : Revista de Teoría de la Literatura y ...,2013-3294,Journal not adhering to Best practice,1677-09-22,2016-10-30
2,a barriguda: revista científica,False,A Barriguda: Revista Científica,2236-6695,Ceased publishing,1677-09-22,2020-04-14
3,a contracorriente,False,A Contracorriente,1548-7083,Journal not adhering to Best practice,1677-09-22,2017-04-27
4,aaup journal of academic freedom,False,AAUP Journal of Academic Freedom,2153-8492,Journal not adhering to Best practice,1677-09-22,2016-11-23
...,...,...,...,...,...,...,...
4227,آب و فاضلاب,False,آب و فاضلاب,2383-0905,Journal not adhering to Best practice,1677-09-22,2022-05-24
4228,اندیشه‌های نوین تربیتی,False,اندیشه‌های نوین تربیتی,2476-7654,Journal not adhering to Best practice,1677-09-22,2022-06-09
4229,مدیریت اسلامی,False,مدیریت اسلامی,2251-6980,Web site URL no longer works,1677-09-22,2021-11-12
4230,پژوهشهای زبان و ادبیات فارسی,False,پژوهشهای زبان و ادبیات فارسی,2008-5486,Inactive (has not published in the last calend...,1677-09-22,2021-11-16
4231,پژوهش‌نامه‌ی آموزش زبان فارسی به غیرفارسی‌زبانان,False,پژوهش‌نامه‌ی آموزش زبان فارسی به غیرفارسی‌زبانان,2676-3354,Journal not adhering to Best practice,1677-09-22,2022-06-15

In [56]:
doaj_remove_label_all_info['Data Source'] = 'DOAJ'

In [57]:
doaj_add_label_all = doaj_all_label[doaj_all_label['added'] == 1].dropna()

In [58]:
doaj_all_label.shape

(17955, 2)

In [59]:
doaj_add_label_all.shape

(13723, 2)

In [60]:
doaj_add_label_all_info = doaj_add_label_all.merge(doaj_add_table_final,on=['Journal_Title_Normalized'])

In [61]:
doaj_add_label_all_info.shape

(13723, 6)

In [62]:
doaj_add_label_all_info.drop_duplicates(subset=['Journal_Title_Normalized'])

,Journal_Title_Normalized,added,Journal Title,ISSN,Remove_Date,Add_Date
0,"#tear: revista de educação, ciência e tecnologia",True,"#Tear: Revista de Educação, Ciência e Tecnologia",2238-8079,1677-09-22,2015-07-20
1,(en)clave comahue,True,(En)clave Comahue,2545-6466,1677-09-22,2019-05-13
2,(پژوهش حسابداری و حسابرسی (پیوسته,True,(پژوهش حسابداری و حسابرسی (پیوسته,2676-7554,1677-09-22,2020-05-25
3,027.7 : zeitschrift für bibliothekskultur,True,027.7 : Zeitschrift für Bibliothekskultur,2296-0597,1677-09-22,2015-12-21
4,100-cs,True,100-Cs,0719-5737,1677-09-22,2018-12-27
...,...,...,...,...,...,...
13718,대한영상의학회지,True,대한영상의학회지,2288-2928,1677-09-22,2019-11-05
13719,선진국방연구,True,선진국방연구,2635-5531,1677-09-22,2019-02-27
13720,치위생과학회지 (journal of dental hygiene sceince),True,치위생과학회지 (journal of Dental Hygiene Sceince),2233-7679,1677-09-22,2020-08-10
13721,한국균학회지,True,한국균학회지,2383-5249,1677-09-22,2019-09-25
13722,한국치위생학회지 (journal of korean society of dental...,True,한국치위생학회지 (Journal of Korean Society of Dental...,2288-2294,1677-09-22,2019-11-20

In [63]:
doaj_add_label_all_info['Reason'] = 'Still in DOAJ index'

In [64]:
doaj_add_label_all_info['Data Source'] = 'DOAJ'

In [65]:
doaj_meta = pd.read_csv('./journal_lists/journalmeta_doaj_20220616.csv')

/home/hzhuang/.local/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3369: DtypeWarning: Columns (46) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [66]:
doaj_meta

,Journal title,Journal URL,URL in DOAJ,When did the journal start to publish all content using an open license?,Alternative title,Journal ISSN (print version),Journal EISSN (online version),Keywords,Languages in which the journal accepts manuscripts,Publisher,...,URL for journal's Open Access statement,Continues,Continued By,LCC Codes,Subjects,DOAJ Seal,Added on Date,Last updated Date,Number of Article Records,Most Recent Article Added
0,Anais da Academia Brasileira de Ciências,http://www.scielo.br/scielo.php?script=sci_ser...,https://doaj.org/toc/ed09859a464f4461b1af34279...,2000.0,Annals of the Brazilian Academy of Sciences,0001-3765,1678-2690,"biological sciences, exact and earth sciences,...",English,Academia Brasileira de Ciências,...,http://www.scielo.br/revistas/aabc/isubscrp.htm,NaN,NaN,Q,Science,No,2004-04-23T21:31:00Z,2017-01-04T14:19:54Z,3668,2022-06-14T07:37:58Z
1,ACME,http://riviste.unimi.it/index.php/ACME,https://doaj.org/toc/b1ca04ba56194f29a362b3eef...,2014.0,NaN,0001-494X,2282-0035,"italian literature, classic literature, lingui...",Italian,Università degli Studi di Milano,...,http://riviste.unimi.it/index.php/ACME/about/e...,NaN,NaN,A,General Works,No,2014-12-22T19:55:58Z,2020-02-24T09:07:42Z,203,2022-05-05T13:31:16Z
2,Acta Biochimica Polonica,https://ojs.ptbioch.edu.pl/index.php/abp,https://doaj.org/toc/eea321d7f4c34a59be8fd1203...,2000.0,NaN,0001-527X,1734-154X,"molecular biology, biophysics, bioinformatics,...",English,Polish Biochemical Society,...,https://ojs.ptbioch.edu.pl/index.php/abp/about,NaN,NaN,QD415-436|QH426-470,Science: Chemistry: Organic chemistry: Biochem...,No,2022-05-23T10:09:09Z,2022-05-23T10:09:09Z,0,NaN
3,Acta Dermato-Venereologica,https://medicaljournalssweden.se/actadv,https://doaj.org/toc/ffde9666ab1d46f1a8c688ce6...,2017.0,NaN,0001-5555,1651-2057,"sexually transmitted infections, psoriasis, ps...",English,Medical Journals Sweden,...,https://medicaljournalssweden.se/actadv/oapolicy,NaN,NaN,RL1-803,Medicine: Dermatology,No,2011-11-10T12:31:05Z,2022-01-05T09:58:42Z,1416,2022-06-15T13:07:06Z
4,Acta Médica Costarricense,http://actamedica.medicos.cr/index.php/Acta_Me...,https://doaj.org/toc/a5919aee5ad2413a89cf32df0...,2019.0,NaN,0001-6012,2215-5856,"medicine, public health, medical sciences, health","English, Spanish",Colegio de Médicos y Cirujanos de Costa Rica,...,http://actamedica.medicos.cr/index.php/Acta_Me...,NaN,NaN,R,Medicine,No,2020-12-22T11:08:24Z,2020-12-22T11:08:24Z,1207,2015-12-08T15:06:43Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17799,Journal of Applied Linguistics and Applied Lit...,http://jalda.azaruniv.ac.ir/,https://doaj.org/toc/3de2348e35374d23afd693055...,2013.0,NaN,2820-8986,NaN,"apppied linguistics, applied literature, criti...",English,"Azarbaijan Shahid Madani University Press,",...,http://jalda.azaruniv.ac.ir/journal/about,NaN,NaN,P,Language and Literature,No,2022-04-03T15:02:09Z,2022-04-03T15:02:09Z,0,NaN
17800,European Bulletin of Himalayan Research,https://preo.u-bourgogne.fr/ebhr,https://doaj.org/toc/33cad422b6e547c0a73e24559...,2018.0,EBHR,NaN,2823-6114,"himalaya, sociology, anthropology, geography, ...",English,Centre National de la Recherche Scientifique (...,...,https://preo.u-bourgogne.fr/ebhr/index.php?id=79,NaN,NaN,G|H1-99|DS1-937,Geography. Anthropology. Recreation | Social S...,No,2022-05-10T05:08:53Z,2022-05-14T11:40:16Z,0,NaN
17801,Educenter,https://jurnal.arkainstitute.co.id/index.php/e...,https://doaj.org/toc/237e5b6c89154b5485650f20a...,2022.0,Educenter: Jurnal Ilmiah Pendidikan,NaN,2827-7988,"education, learning, teaching, pedagogy, e-lea...","English, Indonesian",ARKA INSTITUTE,...,https://jurnal.arkainstitute.co.id/index.php/e...,NaN,NaN,L7-991,Education: Education (General),No,2022-06-08T14:35:10Z,2022-06-08T14:35:10Z,0,NaN
17802,Educational Technology Quarterly,https://acnsci.org/journal/index.php/etq,https://doaj.org/toc/bc6ea21adc534e63bd90bd83e...,2022.0,NaN,NaN,2831-5332,"e-learning, educational technology, mobile lea...",English,Academy of Cognitive and Natural Sciences,...,https://acnsci.org/journal/index.php/etq/opena...,NaN,NaN,L,Education,No,2022-05-30T08:57:01Z,2022-05-30T08:57:01Z,0,NaN
17803,Science of Tsunami Hazards,http://tsunamisociety.org/,https://doaj.org/toc/a4f06be11f4f4db489dc034c7...,2001.0,NaN,8755-6839,2168-6009,"tsunamis, tsunami warning systems, earthquakes...",English,Tsunami Society International,...,http://tsunamisociety.org/InstructionsAuthors....,NaN,NaN,GC1-1581,Geography. Anthropology. Recreation: Oceanography,No,2009-04-16T17:40:30Z,2022-04-28T14:50:44Z,265,2022-05-17T17:16:14Z

In [67]:
def check_date(entry):
    if len(entry)<10:
        return 0
    return 1

In [68]:
doaj_meta['added'] = doaj_meta['Added on Date'].apply(check_date)

In [69]:
doaj_meta

,Journal title,Journal URL,URL in DOAJ,When did the journal start to publish all content using an open license?,Alternative title,Journal ISSN (print version),Journal EISSN (online version),Keywords,Languages in which the journal accepts manuscripts,Publisher,...,Continues,Continued By,LCC Codes,Subjects,DOAJ Seal,Added on Date,Last updated Date,Number of Article Records,Most Recent Article Added,added
0,Anais da Academia Brasileira de Ciências,http://www.scielo.br/scielo.php?script=sci_ser...,https://doaj.org/toc/ed09859a464f4461b1af34279...,2000.0,Annals of the Brazilian Academy of Sciences,0001-3765,1678-2690,"biological sciences, exact and earth sciences,...",English,Academia Brasileira de Ciências,...,NaN,NaN,Q,Science,No,2004-04-23T21:31:00Z,2017-01-04T14:19:54Z,3668,2022-06-14T07:37:58Z,1
1,ACME,http://riviste.unimi.it/index.php/ACME,https://doaj.org/toc/b1ca04ba56194f29a362b3eef...,2014.0,NaN,0001-494X,2282-0035,"italian literature, classic literature, lingui...",Italian,Università degli Studi di Milano,...,NaN,NaN,A,General Works,No,2014-12-22T19:55:58Z,2020-02-24T09:07:42Z,203,2022-05-05T13:31:16Z,1
2,Acta Biochimica Polonica,https://ojs.ptbioch.edu.pl/index.php/abp,https://doaj.org/toc/eea321d7f4c34a59be8fd1203...,2000.0,NaN,0001-527X,1734-154X,"molecular biology, biophysics, bioinformatics,...",English,Polish Biochemical Society,...,NaN,NaN,QD415-436|QH426-470,Science: Chemistry: Organic chemistry: Biochem...,No,2022-05-23T10:09:09Z,2022-05-23T10:09:09Z,0,NaN,1
3,Acta Dermato-Venereologica,https://medicaljournalssweden.se/actadv,https://doaj.org/toc/ffde9666ab1d46f1a8c688ce6...,2017.0,NaN,0001-5555,1651-2057,"sexually transmitted infections, psoriasis, ps...",English,Medical Journals Sweden,...,NaN,NaN,RL1-803,Medicine: Dermatology,No,2011-11-10T12:31:05Z,2022-01-05T09:58:42Z,1416,2022-06-15T13:07:06Z,1
4,Acta Médica Costarricense,http://actamedica.medicos.cr/index.php/Acta_Me...,https://doaj.org/toc/a5919aee5ad2413a89cf32df0...,2019.0,NaN,0001-6012,2215-5856,"medicine, public health, medical sciences, health","English, Spanish",Colegio de Médicos y Cirujanos de Costa Rica,...,NaN,NaN,R,Medicine,No,2020-12-22T11:08:24Z,2020-12-22T11:08:24Z,1207,2015-12-08T15:06:43Z,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17799,Journal of Applied Linguistics and Applied Lit...,http://jalda.azaruniv.ac.ir/,https://doaj.org/toc/3de2348e35374d23afd693055...,2013.0,NaN,2820-8986,NaN,"apppied linguistics, applied literature, criti...",English,"Azarbaijan Shahid Madani University Press,",...,NaN,NaN,P,Language and Literature,No,2022-04-03T15:02:09Z,2022-04-03T15:02:09Z,0,NaN,1
17800,European Bulletin of Himalayan Research,https://preo.u-bourgogne.fr/ebhr,https://doaj.org/toc/33cad422b6e547c0a73e24559...,2018.0,EBHR,NaN,2823-6114,"himalaya, sociology, anthropology, geography, ...",English,Centre National de la Recherche Scientifique (...,...,NaN,NaN,G|H1-99|DS1-937,Geography. Anthropology. Recreation | Social S...,No,2022-05-10T05:08:53Z,2022-05-14T11:40:16Z,0,NaN,1
17801,Educenter,https://jurnal.arkainstitute.co.id/index.php/e...,https://doaj.org/toc/237e5b6c89154b5485650f20a...,2022.0,Educenter: Jurnal Ilmiah Pendidikan,NaN,2827-7988,"education, learning, teaching, pedagogy, e-lea...","English, Indonesian",ARKA INSTITUTE,...,NaN,NaN,L7-991,Education: Education (General),No,2022-06-08T14:35:10Z,2022-06-08T14:35:10Z,0,NaN,1
17802,Educational Technology Quarterly,https://acnsci.org/journal/index.php/etq,https://doaj.org/toc/bc6ea21adc534e63bd90bd83e...,2022.0,NaN,NaN,2831-5332,"e-learning, educational technology, mobile lea...",English,Academy of Cognitive and Natural Sciences,...,NaN,NaN,L,Education,No,2022-05-30T08:57:01Z,2022-05-30T08:57:01Z,0,NaN,1
17803,Science of Tsunami Hazards,http://tsunamisociety.org/,https://doaj.org/toc/a4f06be11f4f4db489dc034c7...,2001.0,NaN,8755-6839,2168-6009,"tsunamis, tsunami warning systems, earthquakes...",English,Tsunami Society International,...,NaN,NaN,GC1-1581,Geography. Anthropology. Recreation: Oceanography,No,2009-04-16T17:40:30Z,2022-04-28T14:50:44Z,265,2022-05-17T17:16:14Z,1

In [70]:
doaj_meta['added'].mean()

1.0

In [71]:
doaj_meta_simple = doaj_meta[['Journal title','Journal URL']]

In [72]:
doaj_meta_simple.rename({'Journal title':'Journal Title',"Journal URL":"URL"}, axis=1, inplace=True)

/home/hzhuang/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [73]:
doaj_meta_simple

,Journal Title,URL
0,Anais da Academia Brasileira de Ciências,http://www.scielo.br/scielo.php?script=sci_ser...
1,ACME,http://riviste.unimi.it/index.php/ACME
2,Acta Biochimica Polonica,https://ojs.ptbioch.edu.pl/index.php/abp
3,Acta Dermato-Venereologica,https://medicaljournalssweden.se/actadv
4,Acta Médica Costarricense,http://actamedica.medicos.cr/index.php/Acta_Me...
...,...,...
17799,Journal of Applied Linguistics and Applied Lit...,http://jalda.azaruniv.ac.ir/
17800,European Bulletin of Himalayan Research,https://preo.u-bourgogne.fr/ebhr
17801,Educenter,https://jurnal.arkainstitute.co.id/index.php/e...
17802,Educational Technology Quarterly,https://acnsci.org/journal/index.php/etq
17803,Science of Tsunami Hazards,http://tsunamisociety.org/

In [74]:
doaj_meta_simple['Journal_Title_Normalized'] = doaj_meta_simple['Journal Title'].str.lower()

/tmp/ipykernel_22781/363537856.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  doaj_meta_simple['Journal_Title_Normalized'] = doaj_meta_simple['Journal Title'].str.lower()

In [75]:
del doaj_meta_simple['Journal Title']

In [172]:
doaj_add_label_all_info.shape

(13723, 8)

In [76]:
doaj_add_all_label_info2 = doaj_add_label_all_info.merge(doaj_meta_simple,on='Journal_Title_Normalized')

In [77]:
doaj_add_all_label_info2.shape

(12985, 9)

In [78]:
doaj_add_all_label_info2['added'].mean()

1.0

In [80]:
doaj_add_all_label_info3 = doaj_add_all_label_info2.drop_duplicates(subset=['Journal_Title_Normalized'])

In [81]:
doaj_add_all_label_info3.shape

(12869, 9)

In [82]:
doaj_remove_label_all_info2 = doaj_remove_label_all_info.merge(doaj_meta_simple,on='Journal_Title_Normalized',how='left')

In [83]:
doaj_remove_label_all_info2

,Journal_Title_Normalized,added,Journal Title,ISSN,Reason,Add_Date,Remove_Date,Data Source,URL
0,3 biotech,False,3 Biotech,2190-5738,Journal is no longer Open Access,1677-09-22,2017-01-06,DOAJ,NaN
1,452º f : revista de teoría de la literatura y ...,False,452º F : Revista de Teoría de la Literatura y ...,2013-3294,Journal not adhering to Best practice,1677-09-22,2016-10-30,DOAJ,NaN
2,a barriguda: revista científica,False,A Barriguda: Revista Científica,2236-6695,Ceased publishing,1677-09-22,2020-04-14,DOAJ,NaN
3,a contracorriente,False,A Contracorriente,1548-7083,Journal not adhering to Best practice,1677-09-22,2017-04-27,DOAJ,NaN
4,aaup journal of academic freedom,False,AAUP Journal of Academic Freedom,2153-8492,Journal not adhering to Best practice,1677-09-22,2016-11-23,DOAJ,NaN
...,...,...,...,...,...,...,...,...,...
4231,آب و فاضلاب,False,آب و فاضلاب,2383-0905,Journal not adhering to Best practice,1677-09-22,2022-05-24,DOAJ,http://wwjournal.ir
4232,اندیشه‌های نوین تربیتی,False,اندیشه‌های نوین تربیتی,2476-7654,Journal not adhering to Best practice,1677-09-22,2022-06-09,DOAJ,NaN
4233,مدیریت اسلامی,False,مدیریت اسلامی,2251-6980,Web site URL no longer works,1677-09-22,2021-11-12,DOAJ,http://im.ihu.ac.ir/?lang=en
4234,پژوهشهای زبان و ادبیات فارسی,False,پژوهشهای زبان و ادبیات فارسی,2008-5486,Inactive (has not published in the last calend...,1677-09-22,2021-11-16,DOAJ,NaN
4235,پژوهش‌نامه‌ی آموزش زبان فارسی به غیرفارسی‌زبانان,False,پژوهش‌نامه‌ی آموزش زبان فارسی به غیرفارسی‌زبانان,2676-3354,Journal not adhering to Best practice,1677-09-22,2022-06-15,DOAJ,NaN

In [85]:
doaj_add_all_label_info2.shape

(12985, 9)

In [86]:
doaj_remove_label_all_info2.dropna(subset=['URL'])

,Journal_Title_Normalized,added,Journal Title,ISSN,Reason,Add_Date,Remove_Date,Data Source,URL
13,acervo,False,Acervo,0102-700X,Journal not adhering to Best practice,1677-09-22,2020-03-06,DOAJ,http://revista.arquivonacional.gov.br/
16,across,False,Across,2602-1463,Inactive (has not published in the last calend...,1677-09-22,2020-05-22,DOAJ,http://www.across-journal.com/index.php/across...
26,acta iguazu,False,Acta Iguazu,2316-4093,Journal not adhering to Best practice,1677-09-22,2017-02-19,DOAJ,http://e-revista.unioeste.br/index.php/actaiguazu
36,acta pharmaceutica,False,Acta Pharmaceutica,1846-9558,Website URL no longer works\n,1677-09-22,2015-08-11,DOAJ,https://sciendo.com/journal/ACPH
43,acta universitaria,False,Acta Universitaria,0188-6266,Ceased publishing,1677-09-22,2015-06-18,DOAJ,http://www.actauniversitaria.ugto.mx/index.php...
...,...,...,...,...,...,...,...,...,...
4217,нанотехнологии в строительстве,False,Нанотехнологии в строительстве,2075-8545,Journal not adhering to Best practice,1677-09-22,2021-03-10,DOAJ,http://nanobuild.ru/
4223,пернатые хищники и их охрана,False,Пернатые хищники и их охрана,1814-0076,Journal not adhering to Best practice,1677-09-22,2021-08-02,DOAJ,http://rusraptors.ru/index.php/RC/index
4225,проект байкал,False,Проект Байкал,2307-4485,Journal not adhering to Best practice,1677-09-22,2021-07-14,DOAJ,https://www.projectbaikal.com/index.php/pb/about
4231,آب و فاضلاب,False,آب و فاضلاب,2383-0905,Journal not adhering to Best practice,1677-09-22,2022-05-24,DOAJ,http://wwjournal.ir
4233,مدیریت اسلامی,False,مدیریت اسلامی,2251-6980,Web site URL no longer works,1677-09-22,2021-11-12,DOAJ,http://im.ihu.ac.ir/?lang=en

In [88]:
doaj_add_all_label_info3.drop_duplicates(subset=['Journal_Title_Normalized'])

,Journal_Title_Normalized,added,Journal Title,ISSN,Remove_Date,Add_Date,Reason,Data Source,URL
0,"#tear: revista de educação, ciência e tecnologia",True,"#Tear: Revista de Educação, Ciência e Tecnologia",2238-8079,1677-09-22,2015-07-20,Still in DOAJ index,DOAJ,https://periodicos.ifrs.edu.br/index.php/tear/...
1,(en)clave comahue,True,(En)clave Comahue,2545-6466,1677-09-22,2019-05-13,Still in DOAJ index,DOAJ,http://revele.uncoma.edu.ar/htdoc/revele/index...
2,(پژوهش حسابداری و حسابرسی (پیوسته,True,(پژوهش حسابداری و حسابرسی (پیوسته,2676-7554,1677-09-22,2020-05-25,Still in DOAJ index,DOAJ,https://ijar.alzahra.ac.ir/
3,100-cs,True,100-Cs,0719-5737,1677-09-22,2018-12-27,Still in DOAJ index,DOAJ,http://100cs.cl/
4,1616,True,1616,0210-7287,1677-09-22,2020-03-09,Still in DOAJ index,DOAJ,http://revistas.usal.es/index.php/1616_Anuario...
...,...,...,...,...,...,...,...,...,...
12980,网络与信息安全学报,True,网络与信息安全学报,2096-109X,1677-09-22,2022-03-01,Still in DOAJ index,DOAJ,http://www.infocomm-journal.com/cjnis/CN/2096-...
12981,陆军军医大学学报,True,陆军军医大学学报,2097-0927,1677-09-22,2022-06-02,Still in DOAJ index,DOAJ,http://aammt.tmmu.edu.cn/
12982,대한영상의학회지,True,대한영상의학회지,2288-2928,1677-09-22,2019-11-05,Still in DOAJ index,DOAJ,https://jksronline.org
12983,선진국방연구,True,선진국방연구,2635-5531,1677-09-22,2019-02-27,Still in DOAJ index,DOAJ,https://journal.idap.re.kr
12984,한국균학회지,True,한국균학회지,2383-5249,1677-09-22,2019-09-25,Still in DOAJ index,DOAJ,http://www.kjmycology.or.kr

In [89]:
doaj_remove_label_all_info2.shape

(4236, 9)

In [90]:
doaj_remove_label_all_info2.drop_duplicates(subset=['Journal_Title_Normalized']).shape

(4232, 9)

In [91]:
doaj_remove_label_all_info3 = doaj_remove_label_all_info2.drop_duplicates(subset=['Journal_Title_Normalized'])

In [92]:
journal_all = pd.concat([doaj_add_all_label_info3,doaj_remove_label_all_info3])

In [93]:
journal_all.shape

(17101, 9)

In [94]:
journal_all.dropna(subset=['Journal_Title_Normalized'])

,Journal_Title_Normalized,added,Journal Title,ISSN,Remove_Date,Add_Date,Reason,Data Source,URL
0,"#tear: revista de educação, ciência e tecnologia",True,"#Tear: Revista de Educação, Ciência e Tecnologia",2238-8079,1677-09-22,2015-07-20,Still in DOAJ index,DOAJ,https://periodicos.ifrs.edu.br/index.php/tear/...
1,(en)clave comahue,True,(En)clave Comahue,2545-6466,1677-09-22,2019-05-13,Still in DOAJ index,DOAJ,http://revele.uncoma.edu.ar/htdoc/revele/index...
2,(پژوهش حسابداری و حسابرسی (پیوسته,True,(پژوهش حسابداری و حسابرسی (پیوسته,2676-7554,1677-09-22,2020-05-25,Still in DOAJ index,DOAJ,https://ijar.alzahra.ac.ir/
3,100-cs,True,100-Cs,0719-5737,1677-09-22,2018-12-27,Still in DOAJ index,DOAJ,http://100cs.cl/
4,1616,True,1616,0210-7287,1677-09-22,2020-03-09,Still in DOAJ index,DOAJ,http://revistas.usal.es/index.php/1616_Anuario...
...,...,...,...,...,...,...,...,...,...
4231,آب و فاضلاب,False,آب و فاضلاب,2383-0905,2022-05-24,1677-09-22,Journal not adhering to Best practice,DOAJ,http://wwjournal.ir
4232,اندیشه‌های نوین تربیتی,False,اندیشه‌های نوین تربیتی,2476-7654,2022-06-09,1677-09-22,Journal not adhering to Best practice,DOAJ,NaN
4233,مدیریت اسلامی,False,مدیریت اسلامی,2251-6980,2021-11-12,1677-09-22,Web site URL no longer works,DOAJ,http://im.ihu.ac.ir/?lang=en
4234,پژوهشهای زبان و ادبیات فارسی,False,پژوهشهای زبان و ادبیات فارسی,2008-5486,2021-11-16,1677-09-22,Inactive (has not published in the last calend...,DOAJ,NaN
4235,پژوهش‌نامه‌ی آموزش زبان فارسی به غیرفارسی‌زبانان,False,پژوهش‌نامه‌ی آموزش زبان فارسی به غیرفارسی‌زبانان,2676-3354,2022-06-15,1677-09-22,Journal not adhering to Best practice,DOAJ,NaN

In [95]:
journal_all.drop_duplicates(subset=['Journal_Title_Normalized'])

,Journal_Title_Normalized,added,Journal Title,ISSN,Remove_Date,Add_Date,Reason,Data Source,URL
0,"#tear: revista de educação, ciência e tecnologia",True,"#Tear: Revista de Educação, Ciência e Tecnologia",2238-8079,1677-09-22,2015-07-20,Still in DOAJ index,DOAJ,https://periodicos.ifrs.edu.br/index.php/tear/...
1,(en)clave comahue,True,(En)clave Comahue,2545-6466,1677-09-22,2019-05-13,Still in DOAJ index,DOAJ,http://revele.uncoma.edu.ar/htdoc/revele/index...
2,(پژوهش حسابداری و حسابرسی (پیوسته,True,(پژوهش حسابداری و حسابرسی (پیوسته,2676-7554,1677-09-22,2020-05-25,Still in DOAJ index,DOAJ,https://ijar.alzahra.ac.ir/
3,100-cs,True,100-Cs,0719-5737,1677-09-22,2018-12-27,Still in DOAJ index,DOAJ,http://100cs.cl/
4,1616,True,1616,0210-7287,1677-09-22,2020-03-09,Still in DOAJ index,DOAJ,http://revistas.usal.es/index.php/1616_Anuario...
...,...,...,...,...,...,...,...,...,...
4231,آب و فاضلاب,False,آب و فاضلاب,2383-0905,2022-05-24,1677-09-22,Journal not adhering to Best practice,DOAJ,http://wwjournal.ir
4232,اندیشه‌های نوین تربیتی,False,اندیشه‌های نوین تربیتی,2476-7654,2022-06-09,1677-09-22,Journal not adhering to Best practice,DOAJ,NaN
4233,مدیریت اسلامی,False,مدیریت اسلامی,2251-6980,2021-11-12,1677-09-22,Web site URL no longer works,DOAJ,http://im.ihu.ac.ir/?lang=en
4234,پژوهشهای زبان و ادبیات فارسی,False,پژوهشهای زبان و ادبیات فارسی,2008-5486,2021-11-16,1677-09-22,Inactive (has not published in the last calend...,DOAJ,NaN
4235,پژوهش‌نامه‌ی آموزش زبان فارسی به غیرفارسی‌زبانان,False,پژوهش‌نامه‌ی آموزش زبان فارسی به غیرفارسی‌زبانان,2676-3354,2022-06-15,1677-09-22,Journal not adhering to Best practice,DOAJ,NaN

In [96]:
import pandas as pd

In [97]:
journal_all.Reason.unique()

array(['Still in DOAJ index', 'Journal is no longer Open Access',
       'Journal not adhering to Best practice', 'Ceased publishing',
       'Journal not adhering to best practice',
       'Web site URL no longer works',
       'Inactive (has not published in the last calender year)',
       'Suspected editorial misconduct by publisher',
       'Inactive (has not published in the last calendar year)',
       'Journal not adhering to Best Practice', 'no OA and licence',
       'Website URL no longer works\n', 'not Open Access',
       'Website URL no longer works', 'inactive',
       'Journal is no longer open access', 'No longer OA',
       'No longer open access', 'Inactive ', 'no licence',
       'Website URLs no longer work', 'stopped publishing',
       "Changed publisher but hasn't supplied new URLs/site",
       'Inactive (not published in 2019)', 'No licence',
       'Has not published enough articles this calendar year',
       'No OA or licence info', 'BMC stopped publishing',
       'no OA statement', 'Website URLs have security issues',
       "Changed publisher but hasn't supplied new url:s/site",
       'Invalid ISSN', 'Inactive journal', 'Missing OA statement',
       'journal not open access', 'ISSN not registered',
       'Web site URL no longer works (Ukrainian)',
       'Journal does not satisfy basic criteria',
       'the print title was added to Doaj',
       'No license nor Open Access statement',
       'Suspected editorial misconduct by society',
       'Inactive (not published since 2018)', 'Inactive',
       'No licence nor OA statement',
       'Inactive (not published since 2017)', 'Not complying to the BOAI',
       'Not a research journal',
       'Journal not adhering to Best practice. Ceased publishing.',
       'no OA statement  no licence', 'few articles published',
       'No longer OA / Inactive (has not published in the last calendar year)',
       'web site url no longer works', 'no OA statement no licence',
       'Journal is not Open Access',
       'Inactive (not published since 2016)',
       'Inactive (not published since 2015)', 'No licence info',
       'Requires user registration', 'Has not published enough articles',
       'Malicious website', 'Web site url no longer works',
       'get warning when trying to open journal',
       'No longer scholarly journal',
       "Journal doesn't adhere to best practice",
       'requires user registration to access PDFs',
       'Publisher will not submit a new application within the given time period for reapplications',
       'Journal is not open access',
       'the issn 20888708 given by editor leads to another journal',
       'Journal not adhering to Best Practice\n',
       'Not enough articles published',
       'Broken Links and No reply to emails', 'Site not secure',
       'no licensing, ', 'application form no info',
       'Journal not adhering to Best practice (one url per issue)',
       'No open access licensing terms', nan,
       'Ceased publishing, continued by 2164-9170',
       'no open access licensing description', 'No editorial board',
       'ceased publication ', 'use of fake impact factor',
       'Invalid contact information',
       'Inactive (has not published since 2016)', 'site unstable',
       'no answer', '24 months embargo ',
       'has not published enough articles this calendar year',
       'No license', '?', 'no licence, no OA statement',
       'Web site url no longer works\n',
       'Has not published enough articles in last calendar year',
       '"     "                    "          "         "',
       'No OA statement', 'No OA statement or licence',
       'Ceased publishing Dec 2019', 'No license nor OA statement',
       'Publisher failed to respond to requests for information',
       'No communication ',
       'Journal not adhering to Best practice, no response',
       'No issue published in 2016',
       'No licence , peer review inadequate', 'No info on license',
       'Journal ceased', "Removed at publisher's request",
       'not open access',
       'Inactive (has not published in the last calendar year, continuation not in DOAJ)',
       'Missing license and copyright statement', 'Embargo on articles',
       'book reviews only', 'journal no longer open access',
       'journal not open access (no statement)',
       'Journal not adhering to Best practice and issn dead', 'dead',
       'Other:website closed by publisher', 'site not secure',
       'site under reconstruction',
       'Ceased publishing + forbidden to open the journal'], dtype=object)

In [98]:
import numpy as np

In [99]:
str(np.nan)

'nan'

In [354]:
def reason_filter(r):
    r =str(r)
    if 'no longer open access' in r.lower() or 'no longer oa' in r.lower() or 'journal not open access' in r.lower() or 'requires user registration to access pdfs' in r.lower():
        return 'ok reason'
    if 'ceased' in r.lower() or 'publication suspended' in r.lower() or 'has not published enough articles in last calendar year' in r.lower():
        return 'ok reason'
    if 'dead' in r.lower() or 'inactive' in r.lower() or 'url no longer works' in r.lower() or 'no working website for the journal' in r.lower():
        return 'ok reason'
    if 'conference journal' in r.lower() or 'book reviews only' in r.lower() or 'repository for conference papers' == r.lower():
        return 'ok reason'
    if 'no longer accepting manuscripts' in r.lower() or 'stopped publishing' in r.lower() or 'has not published enough articles this calendar year' in r.lower() or 'not publishing' in r.lower():
        return 'ok reason'
    if 'no articles published' in r.lower() or 'not published since' in r.lower() or 'no issues since' in r.lower() or 'no longer accepting' in r.lower():
        return 'ok reason'
    if 'incorporated into another journal' in r.lower() or 'merged' in r.lower() or 'combined' in r.lower():
        return 'ok reason'
    if "removed at publisher's request" == r.lower() or 'editor requested we remove the journal.' == r.lower() or "does not directly relate to one of the 18 disciplines currently covered by Cabell's." in r:
        return 'ok reason'
    if '"     "                    "          "         "' == r.lower():
        return 'ok reason'
    if 'the issn 20888708 given by editor leads to another journal' == r.lower() or str(np.nan) == r.lower() or 'no answer' == r.lower():
        return 'ok reason'
    if str(np.nan) == r.lower() or 'new url' in r.lower() or 'site unstable' in r.lower() or 'not open access' in r.lower():
        return 'ok reason'
    if 'website urls no longer work' in r.lower() or 'invalid issn' in r.lower() or 'the print title was added to doaj' in r.lower():
        return 'ok reason'
    if 'other:website closed by publisher' in r.lower() or 'site under reconstruction' in r.lower() or 'not a research journal' in r.lower():
        return 'ok reason'
    if 'publisher will not submit a new application within the given time period for reapplications' in r.lower():
        return 'ok reason'
    if 'no longer scholarly journal' in r.lower() or 'few articles published' in r.lower() or 'no issue published in 2016' in r.lower():
        return 'ok reason'
    if len(r)<=3 and r not in ['A','P']:
        return 'ok reason'
    return 'interesting reason'

In [355]:
journal_all['reason_category'] = journal_all['Reason'].apply(reason_filter)

In [356]:
journal_all.head(10)

,Journal_Title_Normalized,added,Journal Title,ISSN,Remove_Date,Add_Date,Reason,Data Source,URL,reason_category
0,"#tear: revista de educação, ciência e tecnologia",True,"#Tear: Revista de Educação, Ciência e Tecnologia",2238-8079,1677-09-22,2015-07-20,Still in DOAJ index,DOAJ,https://periodicos.ifrs.edu.br/index.php/tear/...,interesting reason
1,(en)clave comahue,True,(En)clave Comahue,2545-6466,1677-09-22,2019-05-13,Still in DOAJ index,DOAJ,http://revele.uncoma.edu.ar/htdoc/revele/index...,interesting reason
2,(پژوهش حسابداری و حسابرسی (پیوسته,True,(پژوهش حسابداری و حسابرسی (پیوسته,2676-7554,1677-09-22,2020-05-25,Still in DOAJ index,DOAJ,https://ijar.alzahra.ac.ir/,interesting reason
3,100-cs,True,100-Cs,0719-5737,1677-09-22,2018-12-27,Still in DOAJ index,DOAJ,http://100cs.cl/,interesting reason
4,1616,True,1616,0210-7287,1677-09-22,2020-03-09,Still in DOAJ index,DOAJ,http://revistas.usal.es/index.php/1616_Anuario...,interesting reason
5,1991. revista de estudios internacionales,True,1991. Revista de Estudios Internacionales,2683-720X,1677-09-22,2020-06-01,Still in DOAJ index,DOAJ,https://revistas.unc.edu.ar/index.php/revesint...,interesting reason
6,"21: inquiries into art, history, and the visual",True,"21: Inquiries into Art, History, and the Visual",2701-1569,1677-09-22,2021-01-13,Still in DOAJ index,DOAJ,https://journals.ub.uni-heidelberg.de/index.ph...,interesting reason
7,2i revista de estudos de identidade e intermed...,True,2i Revista de Estudos de Identidade e Intermed...,2184-7010,1677-09-22,2021-05-06,Still in DOAJ index,DOAJ,https://revistas.uminho.pt/index.php/2i/,interesting reason
8,360,True,360,2415-5861,1677-09-22,2019-05-13,Still in DOAJ index,DOAJ,http://revistas.pucp.edu.pe/360gestion,interesting reason
9,3c tic,True,3C TIC,2254-6529,1677-09-22,2016-01-08,Still in DOAJ index,DOAJ,http://ojs.3ciencias.com/index.php/3c-tic/index,interesting reason

In [357]:
journal_all_interesting = journal_all[journal_all['reason_category'] == 'interesting reason']

In [358]:
journal_all_interesting.head(3)

,Journal_Title_Normalized,added,Journal Title,ISSN,Remove_Date,Add_Date,Reason,Data Source,URL,reason_category
0,"#tear: revista de educação, ciência e tecnologia",True,"#Tear: Revista de Educação, Ciência e Tecnologia",2238-8079,1677-09-22,2015-07-20,Still in DOAJ index,DOAJ,https://periodicos.ifrs.edu.br/index.php/tear/...,interesting reason
1,(en)clave comahue,True,(En)clave Comahue,2545-6466,1677-09-22,2019-05-13,Still in DOAJ index,DOAJ,http://revele.uncoma.edu.ar/htdoc/revele/index...,interesting reason
2,(پژوهش حسابداری و حسابرسی (پیوسته,True,(پژوهش حسابداری و حسابرسی (پیوسته,2676-7554,1677-09-22,2020-05-25,Still in DOAJ index,DOAJ,https://ijar.alzahra.ac.ir/,interesting reason

In [359]:
journal_all_interesting[journal_all_interesting['ISSN']=='2218-4511']

Empty DataFrame
Columns: [Journal_Title_Normalized, added, Journal Title, ISSN, Remove_Date, Add_Date, Reason, Data Source, URL, reason_category]
Index: []

In [360]:
journal_all_interesting.shape

(15517, 10)

In [361]:
journal_all_interesting[journal_all_interesting['Reason'] == 'Still in DOAJ index'].shape

(12869, 10)

In [362]:
journal_all_interesting.dropna(subset=['Reason']).shape

(15517, 10)

In [363]:
journal_all_interesting.shape

(15517, 10)

In [364]:
journal_all_interesting.head(5)

,Journal_Title_Normalized,added,Journal Title,ISSN,Remove_Date,Add_Date,Reason,Data Source,URL,reason_category
0,"#tear: revista de educação, ciência e tecnologia",True,"#Tear: Revista de Educação, Ciência e Tecnologia",2238-8079,1677-09-22,2015-07-20,Still in DOAJ index,DOAJ,https://periodicos.ifrs.edu.br/index.php/tear/...,interesting reason
1,(en)clave comahue,True,(En)clave Comahue,2545-6466,1677-09-22,2019-05-13,Still in DOAJ index,DOAJ,http://revele.uncoma.edu.ar/htdoc/revele/index...,interesting reason
2,(پژوهش حسابداری و حسابرسی (پیوسته,True,(پژوهش حسابداری و حسابرسی (پیوسته,2676-7554,1677-09-22,2020-05-25,Still in DOAJ index,DOAJ,https://ijar.alzahra.ac.ir/,interesting reason
3,100-cs,True,100-Cs,0719-5737,1677-09-22,2018-12-27,Still in DOAJ index,DOAJ,http://100cs.cl/,interesting reason
4,1616,True,1616,0210-7287,1677-09-22,2020-03-09,Still in DOAJ index,DOAJ,http://revistas.usal.es/index.php/1616_Anuario...,interesting reason

In [365]:
journal_all_interesting_unique = journal_all_interesting.drop_duplicates(subset=['Journal_Title_Normalized'], keep='last').\
                                 reset_index(drop=True).\
                                 dropna(subset=['ISSN'])

In [366]:
journal_all_interesting_unique.shape

(15515, 10)

In [367]:
journal_all_interesting.shape

(15517, 10)

In [368]:
journal_all_interesting_unique.to_csv('doaj_journal_list_interesting.csv',index=False)

In [369]:
journal_all_interesting_unique[journal_all_interesting_unique['added']==False].shape

(2646, 10)

In [370]:
journal_all_interesting_unique_with_url_doaj = journal_all_interesting_unique[~journal_all_interesting_unique['URL'].isnull()]

In [371]:
journal_all_interesting_unique_with_url_doaj.shape

(12995, 10)

In [372]:
journal_all_interesting_unique_with_url_doaj['Reason'].unique()

array(['Still in DOAJ index', 'Journal not adhering to Best practice',
       'Suspected editorial misconduct by publisher',
       'Journal not adhering to best practice',
       'Journal not adhering to Best Practice', 'Missing OA statement',
       'no licence', 'get warning when trying to open journal',
       'No licence', 'No OA statement', 'No OA or licence info'],
      dtype=object)

In [373]:
journal_all_interesting_unique_with_url_doaj.to_csv('doaj_journal_list_with_urls_from_doaj.csv',index=False)

In [374]:
13001+2547

15548

In [375]:
journal_all_interesting_unique_no_url = journal_all_interesting_unique[journal_all_interesting_unique['URL'].isnull()]

In [376]:
journal_all_interesting_unique_no_url.shape

(2520, 10)

In [377]:
journal_all_interesting_unique_no_url[journal_all_interesting_unique_no_url['added']==False]

,Journal_Title_Normalized,added,Journal Title,ISSN,Remove_Date,Add_Date,Reason,Data Source,URL,reason_category
12869,452º f : revista de teoría de la literatura y ...,False,452º F : Revista de Teoría de la Literatura y ...,2013-3294,2016-10-30,1677-09-22,Journal not adhering to Best practice,DOAJ,NaN,interesting reason
12870,a contracorriente,False,A Contracorriente,1548-7083,2017-04-27,1677-09-22,Journal not adhering to Best practice,DOAJ,NaN,interesting reason
12871,aaup journal of academic freedom,False,AAUP Journal of Academic Freedom,2153-8492,2016-11-23,1677-09-22,Journal not adhering to Best practice,DOAJ,NaN,interesting reason
12872,abant kültürel araştırmalar dergisi,False,Abant Kültürel Araştırmalar Dergisi,2528-9403,2020-05-18,1677-09-22,Journal not adhering to best practice,DOAJ,NaN,interesting reason
12873,academia anatomica international,False,Academia Anatomica International,2455-5274,2017-11-14,1677-09-22,Suspected editorial misconduct by publisher,DOAJ,NaN,interesting reason
...,...,...,...,...,...,...,...,...,...,...
15511,силовое и энергетическое оборудование: автоном...,False,Силовое и энергетическое оборудование: Автоном...,2618-8716,2020-11-19,1677-09-22,Website URLs have security issues,DOAJ,NaN,interesting reason
15512,українська біографістика,False,Українська біографістика,2520-2855,2021-02-11,1677-09-22,Journal not adhering to best practice,DOAJ,NaN,interesting reason
15513,экономика региона,False,Экономика региона,2072-6414,2021-03-01,1677-09-22,Journal not adhering to Best practice,DOAJ,NaN,interesting reason
15515,اندیشه‌های نوین تربیتی,False,اندیشه‌های نوین تربیتی,2476-7654,2022-06-09,1677-09-22,Journal not adhering to Best practice,DOAJ,NaN,interesting reason
15516,پژوهش‌نامه‌ی آموزش زبان فارسی به غیرفارسی‌زبانان,False,پژوهش‌نامه‌ی آموزش زبان فارسی به غیرفارسی‌زبانان,2676-3354,2022-06-15,1677-09-22,Journal not adhering to Best practice,DOAJ,NaN,interesting reason

In [378]:
journal_all_interesting_unique_no_url['Reason'].unique()

array(['Journal not adhering to Best practice',
       'Journal not adhering to best practice',
       'Suspected editorial misconduct by publisher',
       'Journal not adhering to Best Practice', 'no OA and licence',
       'no licence', 'No licence', 'No OA or licence info',
       'no OA statement', 'Website URLs have security issues',
       'Missing OA statement', 'ISSN not registered',
       'Journal does not satisfy basic criteria',
       'No license nor Open Access statement',
       'Suspected editorial misconduct by society',
       'No licence nor OA statement', 'Not complying to the BOAI',
       'no OA statement  no licence', 'no OA statement no licence',
       'No licence info', 'Requires user registration',
       'Has not published enough articles', 'Malicious website',
       "Journal doesn't adhere to best practice",
       'Journal not adhering to Best Practice\n',
       'Not enough articles published',
       'Broken Links and No reply to emails', 'Site not secure',
       'no licensing, ', 'application form no info',
       'Journal not adhering to Best practice (one url per issue)',
       'No open access licensing terms',
       'no open access licensing description', 'No editorial board',
       'use of fake impact factor', 'Invalid contact information',
       '24 months embargo ', 'No license', 'no licence, no OA statement',
       'No OA statement or licence', 'No license nor OA statement',
       'Publisher failed to respond to requests for information',
       'No communication ',
       'Journal not adhering to Best practice, no response',
       'No OA statement', 'No licence , peer review inadequate',
       'No info on license', 'Missing license and copyright statement',
       'Embargo on articles', 'site not secure'], dtype=object)

In [379]:
journal_all_interesting_unique_no_url.to_csv('doaj_journal_list_need_urls.csv',index=False)

# unpaywall in DOAJ

In [3]:
import pandas as pd

In [4]:
doaj_journals = pd.read_csv('doaj_journal_list_interesting.csv')

In [7]:
doaj_journals[doaj_journals['Reason']=='Still in DOAJ index'].shape

(12869, 10)

In [8]:
doaj_journals[doaj_journals['Reason']!='Still in DOAJ index'].shape

(2646, 10)

In [15]:
doaj_journals.head(4)

,Journal_Title_Normalized,added,Journal Title,ISSN,Remove_Date,Add_Date,Reason,Data Source,URL,reason_category
0,"#tear: revista de educação, ciência e tecnologia",True,"#Tear: Revista de Educação, Ciência e Tecnologia",2238-8079,1677-09-22,2015-07-20,Still in DOAJ index,DOAJ,https://periodicos.ifrs.edu.br/index.php/tear/...,interesting reason
1,(en)clave comahue,True,(En)clave Comahue,2545-6466,1677-09-22,2019-05-13,Still in DOAJ index,DOAJ,http://revele.uncoma.edu.ar/htdoc/revele/index...,interesting reason
2,(پژوهش حسابداری و حسابرسی (پیوسته,True,(پژوهش حسابداری و حسابرسی (پیوسته,2676-7554,1677-09-22,2020-05-25,Still in DOAJ index,DOAJ,https://ijar.alzahra.ac.ir/,interesting reason
3,100-cs,True,100-Cs,0719-5737,1677-09-22,2018-12-27,Still in DOAJ index,DOAJ,http://100cs.cl/,interesting reason

In [19]:
doaj_journals['ISSN'] = doaj_journals['ISSN'].apply(str.strip)

In [20]:
doaj_journals['Journal_Title_Normalized'] = doaj_journals['Journal_Title_Normalized'].apply(str.strip)

In [28]:
unpaywall = pd.read_csv('unpaywall_in_MAG_v1.csv')

In [11]:
unpaywall['Issn'] = unpaywall['journal_issns'].apply(get_first_ISSN)

In [29]:
unpaywall

,Issn,NormalizedName,JournalId
0,1015-8987,cellular physiology and biochemistry,161399637
1,0165-5701,international ophthalmology,47727624
2,0021-9002,journal of applied probability,160779208
3,1759-4758,nature reviews neurology,22232893
4,1868-7075,clinical epigenetics,200416800
...,...,...,...
25343,1082-7579,medical update for psychiatrists,58951593
25344,2155-6199,journal of bioremediation and biodegradation,2764664074
25345,2452-1760,advances in ophthalmology and optometry,2898386384
25346,2055-1266,journal of biomedical engineering and medical ...,2764986136
25347,2329-9096,international journal of physical medicine and...,2764660091

In [30]:
to_match1 = unpaywall.dropna(subset=['Issn']).drop_duplicates(subset=['Issn'])

In [31]:
to_match2 = unpaywall.dropna(subset=['NormalizedName']).drop_duplicates(subset=['NormalizedName'])

In [32]:
to_match1_0 = to_match1[to_match1['Issn'].isin(doaj_journals['ISSN'])]

In [33]:
to_match1_0.shape

(2081, 3)

In [34]:
to_match2_0 = to_match2[to_match2['NormalizedName'].isin(doaj_journals['Journal_Title_Normalized'])]

In [35]:
to_match2_0.shape

(2854, 3)

In [38]:
all_match = pd.concat([to_match1_0,to_match2_0]).drop_duplicates(subset=['JournalId'])

In [39]:
all_match.shape

(3216, 3)

# get urls from Bing